### ISSUE TITLE
[feature] 백엔드 데이터베이스 연동 및 API 라우팅 기본 베이스 작성

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/deal-12#53]
## TODO

- [x] EC2 배포 서버에 데이터베이스 연결
- [x] 데이터베이스 조작 커넥션 및 질의 수행문 함수로 작성
- [x] 라우팅 기본 베이스 작성
